# coding=gbk

def main():
    str = '"{"Title":"李秀芬与被告郭秀艳民间借贷纠纷案一审民事裁定书","PubDate":"2017-03-30","Html":"<a type=\'dir\' name=\'WBSB\'></a><div style=\'TEXT-ALIGN: center; LINE-HEIGHT: 25pt; MARGIN: 0.5pt 0cm; FONT-FAMILY: 宋体; FONT-SIZE: 22pt;\'>黑龙江省海林市人民法院</div><a type=\'dir\' name=\'AJJBQK\'></a><div style=\'TEXT-ALIGN: center; LINE-HEIGHT: 30pt; MARGIN: 0.5pt 0cm; FONT-FAMILY: 仿宋; FONT-SIZE: 26pt;\'>民 事 裁 定 书</div><div style=\'TEXT-ALIGN: right; LINE-HEIGHT: 30pt; MARGIN: 0.5pt 0cm;  FONT-FAMILY: 仿宋;FONT-SIZE: 16pt; \'>(2017)黑1083民初56号</div><div style=\'LINE-HEIGHT: 25pt;TEXT-ALIGN:justify;TEXT-JUSTIFY:inter-ideograph; TEXT-INDENT: 30pt; MARGIN: 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>原告：李秀芬，女，1964年6月17日出生，汉族。</div><div style=\'LINE-HEIGHT: 25pt;TEXT-ALIGN:justify;TEXT-JUSTIFY:inter-ideograph; TEXT-INDENT: 30pt; MARGIN: 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>被告：郭秀艳，女，汉族。</div><div style=\'LINE-HEIGHT: 25pt;TEXT-ALIGN:justify;TEXT-JUSTIFY:inter-ideograph; TEXT-INDENT: 30pt; MARGIN: 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>原告李秀芬与被告郭秀艳民间借贷纠纷一案，本院于2017年1月6日立案。原告李秀芬于2017年3月22日向本院提出撤诉申请。</div><a type=\'dir\' name=\'CPYZ\'></a><div style=\'LINE-HEIGHT: 25pt;TEXT-ALIGN:justify;TEXT-JUSTIFY:inter-ideograph; TEXT-INDENT: 30pt; MARGIN: 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>本院认为，李秀芬与郭秀艳案外达成和解并申请撤回起诉，符合法律规定。</div><div style=\'LINE-HEIGHT: 25pt;TEXT-ALIGN:justify;TEXT-JUSTIFY:inter-ideograph; TEXT-INDENT: 30pt; MARGIN: 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>依照《中华人民共和国民事诉讼法》第一百四十五条第一款的规定，裁定如下：</div><a type=\'dir\' name=\'PJJG\'></a><div style=\'LINE-HEIGHT: 25pt;TEXT-ALIGN:justify;TEXT-JUSTIFY:inter-ideograph; TEXT-INDENT: 30pt; MARGIN: 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>准许李秀芬撤诉。</div><div style=\'LINE-HEIGHT: 25pt;TEXT-ALIGN:justify;TEXT-JUSTIFY:inter-ideograph; TEXT-INDENT: 30pt; MARGIN: 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>案件受理费800元，减半收取计400元，由李秀芬负担。</div><a type=\'dir\' name=\'WBWB\'></a><div style=\'TEXT-ALIGN: right; LINE-HEIGHT: 25pt; MARGIN: 0.5pt 72pt 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>审判员　　潘远成</div><br/><div style=\'TEXT-ALIGN: right; LINE-HEIGHT: 25pt; MARGIN: 0.5pt 72pt 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>二〇一七年三月二十二日</div><div style=\'TEXT-ALIGN: right; LINE-HEIGHT: 25pt; MARGIN: 0.5pt 72pt 0.5pt 0cm;FONT-FAMILY: 仿宋; FONT-SIZE: 16pt;\'>书记员　　周家鹏</div>"}";'
    print(str.split('Title":"')[1].split('","PubDate')[0])
    print(str.split('PubDate":"')[1].split('","Html')[0])
    print(str.split('Html":"')[1].split('"}";')[0])


if __name__ == '__main__':
    main()
